---
title: "JSC370 Final Project"
author: "Cathy Pei"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

This is my JSC370 Final Project website.
```{r eval=TRUE, include=FALSE}
# code from week 11 lab
library(tidyverse)
library(plotly)
library(widgetframe)
library(tidytext)
library(dplyr)
library(readr)

### load Starbucks and state-level data ###
sb_locs <- read_csv("https://raw.githubusercontent.com/JSC370/JSC370-2024/main/labs/lab11/starbucks-locations.csv")

sb_nutr <- read_csv("https://raw.githubusercontent.com/JSC370/JSC370-2024/main/labs/lab11/starbucks-menu-nutrition.csv")

usa_pop <- read_csv("https://raw.githubusercontent.com/JSC370/JSC370-2024/main/labs/lab11/us_state_pop.csv")

usa_states<-read_csv("https://raw.githubusercontent.com/JSC370/JSC370-2024/main/labs/lab11/states.csv")


### Merge data ###
sb_usa <- sb_locs |> filter(Country=="US")

sb_locs_state <- sb_usa |>
  group_by(`State/Province`) |>
  rename(state=`State/Province`) |>
  summarize(n_stores=n())

# need state abbreviations
usa_pop_abbr <- 
  full_join(usa_pop, usa_states, 
            by = join_by(state == State)
  ) 

sb_locs_state <- full_join(sb_locs_state, usa_pop_abbr,
                           by = join_by (state == Abbreviation))


### Get topwords from menu items ###

topwords <- sb_nutr |>
  unnest_tokens(word, Item, token="words") |>
  group_by(word) |>
  summarise(word_frequency = n()) |>
  arrange(across(word_frequency, desc)) |>
  head(10)

```

```{r plot1, eval=TRUE, echo=FALSE}
sb_nutr <- sb_nutr %>%
  rename(Carbs = 'Carb. (g)')
sb_nutr <- sb_nutr %>%
  rename(Fat = 'Fat (g)')
sb_nutr <- sb_nutr %>%
  rename(Fiber = 'Fiber (g)')
sb_nutr <- sb_nutr %>%
  rename(Protein = 'Protein (g)')

top_10_words <- topwords %>% pull(word)

# Filter items containing the top 10 words
filtered_items <- sb_nutr %>%
  filter(str_detect(tolower(Item), paste(top_10_words, collapse = "|")))
scatterplot_3d <- plot_ly(filtered_items, x = ~Calories, y = ~Carbs, z = ~Protein,
                          type = "scatter3d", mode = "markers",
                          marker = list(size = 5)) %>%
  layout(scene = list(xaxis = list(title = "Calories"),
                      yaxis = list(title = "Carbs"),
                      zaxis = list(title = "Protein")),
         title = "3D Scatterplot of Calories, Carbs, and Protein for Items Containing Top 10 Words")


```

```{r plot2, eval=TRUE, echo=FALSE}
# Set up mapping details
set_map_details <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('steelblue')
)

# Make sure both maps are on the same color scale
shadeLimit <- 125

loc_filtered <- sb_locs_state[!is.na(sb_locs_state$n_stores), ]

# Create hover text for map 1
hover_text_map1 <- with(sb_locs_state, paste("Number of Starbucks: ", n_stores, '<br>', "State: ", state.y, '<br>'))

# Create the map for number of stores per state
map1 <- plot_geo(locationmode = 'USA-states') %>%
  add_trace(data = sb_locs_state,
            z = ~n_stores,  # Values to represent on the map
            locations = ~state,  # Locations (state names)
            text = hover_text_map1,  # Hover text
            color = ~n_stores,
            colors = 'Blues',  # Color scale
            colorbar = list(title = "Number of Starbucks")) %>%
  layout(title = "Number of Starbucks Stores per State", geo = set_map_details)

# Create hover text for map 2
hover_text_map2 <- with(sb_locs_state, paste("Population: ", population, '<br>', "State: ", state.y, '<br>'))

# Create the map for population by state
map2 <- plot_geo(locationmode = 'USA-states') %>%
  add_trace(data = sb_locs_state,
            z = ~population,  # Values to represent on the map
            locations = ~state,  # Locations (state names)
            text = hover_text_map2,  # Hover text
            color = ~population,
            colors = 'Blues',  # Color scale
            colorbar = list(title = "Population")) %>%
  layout(title = "Population by State", geo = set_map_details)

```

## Showcasing plots {.tabset}

### Figure 1

```{r echo=FALSE}
scatterplot_3d
```

### Figure 2

```{r echo=FALSE}
subplot(map1, map2)
```

{-}